# Cafe88 POS modulecatalogus
catalog.version=1
catalog.modules=CASH_CHANGE,CASH_CHECK,INVENTORY,INVENTORY_CHECK,SHOPPING_LIST,COCKTAILS,CUSTOMERS
module.CASH_CHANGE.version=0.5.71
module.CASH_CHANGE.pos.required.version=0.5.71
module.CASH_CHANGE.requires=
module.CASH_CHANGE.download=module-cashchange-0.5.71.jar
module.CASH_CHANGE.sha256=d63ad8f741d77f8926c0b80d30e116193308573794c0bc9b128b6e95d7128c69
module.CASH_CHECK.version=0.5.71
module.CASH_CHECK.pos.required.version=0.5.71
module.CASH_CHECK.requires=
module.CASH_CHECK.download=module-cashcheck-0.5.71.jar
module.CASH_CHECK.sha256=964f6a9d915b4864432ecabd43f67d9380db963e3d09f82c5746620cdcda7a5e
module.INVENTORY.version=0.5.71
module.INVENTORY.pos.required.version=0.5.71
module.INVENTORY.requires=
module.INVENTORY.download=module-inventory-0.5.71.jar
module.INVENTORY.sha256=416effb2afee4dde8604e195fa4099d38add7ca1fc353d895532960c0ba0dacf
module.INVENTORY_CHECK.version=0.5.71
module.INVENTORY_CHECK.pos.required.version=0.5.71
module.INVENTORY_CHECK.requires=INVENTORY
module.INVENTORY_CHECK.download=module-inventorycheck-0.5.71.jar
module.INVENTORY_CHECK.sha256=109dcb19762404125b6ab9ddcbdef1ced876ec75e71d341b403af8e96a37b0f0
module.SHOPPING_LIST.version=0.5.71
module.SHOPPING_LIST.pos.required.version=0.5.71
module.SHOPPING_LIST.requires=INVENTORY
module.SHOPPING_LIST.download=module-shoppinglist-0.5.71.jar
module.SHOPPING_LIST.sha256=34e1ad180aad824a487ebd81b2b71ad5425fbc9f4483efacb4c5a34ef26ccfeb
module.COCKTAILS.version=0.5.71
module.COCKTAILS.pos.required.version=0.5.71
module.COCKTAILS.requires=
module.COCKTAILS.download=module-cocktails-0.5.71.jar
module.COCKTAILS.sha256=c4f6e74d6eb12dec83036c571f69a8971e453e1145824469bf97295f01ce27c2
module.CUSTOMERS.version=0.5.71
module.CUSTOMERS.pos.required.version=0.5.71
module.CUSTOMERS.requires=
module.CUSTOMERS.download=module-customer-0.5.71.jar
module.CUSTOMERS.sha256=4bad34216238ed3881b2aed3670e51b218b6f5e19c9acb415210293948dd9804
