# Cafe88 POS modulecatalogus
catalog.version=1
catalog.modules=CASH_CHANGE,CASH_CHECK,INVENTORY,INVENTORY_CHECK,SHOPPING_LIST,COCKTAILS,CUSTOMERS
module.CASH_CHANGE.version=0.5.15
module.CASH_CHANGE.pos.required.version=0.5.15
module.CASH_CHANGE.requires=
module.CASH_CHANGE.download=module-cashchange-0.5.15.jar
module.CASH_CHANGE.sha256=209260f953b95202f5ad3f88377182fb3340715f69fb53aef47e8c90e8db6ab5
module.CASH_CHECK.version=0.5.15
module.CASH_CHECK.pos.required.version=0.5.15
module.CASH_CHECK.requires=
module.CASH_CHECK.download=module-cashcheck-0.5.15.jar
module.CASH_CHECK.sha256=88f1570c4bfc10188ca10ca45eaf004f2fe506e650623038cca4a36d525cc6c3
module.INVENTORY.version=0.5.15
module.INVENTORY.pos.required.version=0.5.15
module.INVENTORY.requires=
module.INVENTORY.download=module-inventory-0.5.15.jar
module.INVENTORY.sha256=c4c4e2a933660290304ce255aedce0d0e3cab3f52bd7438cdad9c39cf0e2e492
module.INVENTORY_CHECK.version=0.5.15
module.INVENTORY_CHECK.pos.required.version=0.5.15
module.INVENTORY_CHECK.requires=INVENTORY
module.INVENTORY_CHECK.download=module-inventorycheck-0.5.15.jar
module.INVENTORY_CHECK.sha256=7034bcfae48e50e58c4842c2ba22c0ce6ce7b612e0f82c232ae27316e9871323
module.SHOPPING_LIST.version=0.5.15
module.SHOPPING_LIST.pos.required.version=0.5.15
module.SHOPPING_LIST.requires=INVENTORY
module.SHOPPING_LIST.download=module-shoppinglist-0.5.15.jar
module.SHOPPING_LIST.sha256=f70630645b058a3818f931fab27d6040fb1b282894b9fbc63238cae672df3c6a
module.COCKTAILS.version=0.5.15
module.COCKTAILS.pos.required.version=0.5.15
module.COCKTAILS.requires=
module.COCKTAILS.download=module-cocktails-0.5.15.jar
module.COCKTAILS.sha256=d510f637846d25228735b2325e65a1cb660355460a2e80baf10d1200d87e1c1a
module.CUSTOMERS.version=0.5.15
module.CUSTOMERS.pos.required.version=0.5.15
module.CUSTOMERS.requires=
module.CUSTOMERS.download=module-customer-0.5.15.jar
module.CUSTOMERS.sha256=9affe811620e4f85eda444715061deec123e9c6b02c612923603c17caa4d030a
