# Cafe88 POS modulecatalogus
catalog.version=1
catalog.modules=CASH_CHANGE,CASH_CHECK,INVENTORY,INVENTORY_CHECK,SHOPPING_LIST,COCKTAILS,CUSTOMERS
module.CASH_CHANGE.version=0.5.81
module.CASH_CHANGE.pos.required.version=0.5.81
module.CASH_CHANGE.requires=
module.CASH_CHANGE.download=module-cashchange-0.5.81.jar
module.CASH_CHANGE.sha256=5c818135dd417ae211633d9b92e44965ea737a5511f362e47255db5c26f821a5
module.CASH_CHECK.version=0.5.81
module.CASH_CHECK.pos.required.version=0.5.81
module.CASH_CHECK.requires=
module.CASH_CHECK.download=module-cashcheck-0.5.81.jar
module.CASH_CHECK.sha256=f95fe420f0b63cf39ec54ad520cc491fee3bddd6d357b02d152ffb5466c53415
module.INVENTORY.version=0.5.81
module.INVENTORY.pos.required.version=0.5.81
module.INVENTORY.requires=
module.INVENTORY.download=module-inventory-0.5.81.jar
module.INVENTORY.sha256=de4488d70d5ab6b18340256ec98fe08886e55ff7f2d17c2c70b764fc5399e7e5
module.INVENTORY_CHECK.version=0.5.81
module.INVENTORY_CHECK.pos.required.version=0.5.81
module.INVENTORY_CHECK.requires=INVENTORY
module.INVENTORY_CHECK.download=module-inventorycheck-0.5.81.jar
module.INVENTORY_CHECK.sha256=fdf3e83762a36750b855934b6ae12e6ccd5c15bb8e5284df5c5f536d6926b920
module.SHOPPING_LIST.version=0.5.81
module.SHOPPING_LIST.pos.required.version=0.5.81
module.SHOPPING_LIST.requires=INVENTORY
module.SHOPPING_LIST.download=module-shoppinglist-0.5.81.jar
module.SHOPPING_LIST.sha256=fb3b2761333f995a21eb4e274cf22d293a0e34521f854187fd02a4c54e21a452
module.COCKTAILS.version=0.5.81
module.COCKTAILS.pos.required.version=0.5.81
module.COCKTAILS.requires=
module.COCKTAILS.download=module-cocktails-0.5.81.jar
module.COCKTAILS.sha256=7b8401ed69747b722d9665c798765729457f03445a769c48e90cacef73747df9
module.CUSTOMERS.version=0.5.81
module.CUSTOMERS.pos.required.version=0.5.81
module.CUSTOMERS.requires=
module.CUSTOMERS.download=module-customer-0.5.81.jar
module.CUSTOMERS.sha256=1cdcc485d5f9bb2f4facae27fe9c9cba4781f402cb289400c4c357c69851d346
